#security:
#  com.jacky.strive.api.oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      scope: read,write
#      auto-approve-scopes: '.*'
#  user:
#    password: password

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/com.jacky.strive.api.oauth2?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  session:
    cookie: JAuth
  servlet:
    context-path: /admin
  port: 8088

logging:
  level:
    org.springframework.security: DEBUG