#适用于通过oauth2.0搭建自己的认证服务器进行认证的resource服务(rest-api)
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8088/admin/oauth/token
      user-authorization-uri: http://localhost:8088/admin/oauth/authorize
      scope: web
    resource:
      user-info-uri: http://localhost:8088/admin/me
      token-info-uri: http://localhost:8088/admin/oauth/check_token